# Generated by Django 4.0 on 2021-12-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('lap_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=32)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('processor', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
